### ISSUE TITLE
Crash with Bumble Llama and Cocoa

### ISSUE THREAD

**Issue by Stygiannite** [ArshiaDPG/Llamarama#13]
https://pastebin.com/cCitDakN

**Comment by 0xJoeMama** [comment]
Thank you for reporting! However, I would like to ask some extra questions if you would be up to that. Firstly, how would I be able to recreate this bug. Also, did it just happen at some point randomly or is it continuously happening? Furthermore, if it happened randomly, what where you doing at the time? Finally, are there any mods in your minecraft instance that may alter the behavior of cocoa beans?

**Comment by 0xJoeMama** [comment]
I believe I have found the issue. Mojang is doing this one weirdly because they should be using `canGrow` instead of always returning true. That is however an issue that can be handled without nuking that game.

Relevant vanilla implementation:
![21-03-2022::19:52](https://user-images.githubusercontent.com/46004440/159334110-33c8cda2-7029-412b-9746-493ad93082dc.png)

Handling on our end:
![21-03-2022::19:50](https://user-images.githubusercontent.com/46004440/159333852-8668aae9-4f14-46ef-9e97-9fa4da5d8e2e.png)

**Comment by 0xJoeMama** [comment]
Well, I think you can tell, you won't need to answer the questions above. Sorry for that. And again, thanks for letting us know about this.
