### ISSUE TITLE
Caravan Trader crashma

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArshiaDPG/Llamarama#24]
**Describe the bug**
Server crashed, found this in my crash-reports folder.

**Expected behavior**
Do not crash.

**Game Instance Information:**
- Game Version.
1.18.2
- Are there other mods in your instance?
600+ Mods

**Crash Information(if relevant):**
https://bytebin.lucko.me/JcCZxgWQil

**Comment by 0xJoeMama** [comment]
Well, there isn't sufficient evidence in the crash log for me to understand the issue. The only thing I could think of,  is the fact that a mutable block pos is being passed into canSpawn. I can just hardcode a toImmutable call and that should be fixed. However I cannot guarantee this will fix the issue. The only reason I think this might be it, is the fact that the crash happened at a *really* low level Java API class instead of a mod. Thanks for the report! Await changes.

**Comment by 0xJoeMama** [comment]
Switched to using a different spawn check. If this also causes crashes let us know.
