### ISSUE TITLE
Llamarama Traders Not Spawning

### ISSUE THREAD

**Issue by MachuMachu** [ArshiaDPG/Llamarama#29]
The wandering traders added by the mod are not spawning as intended.

The llamarama group has spawned more than a couple of times. All the llamas are present, but without the trader. Didn't noticed any leads dropped anywhere, like how vanilla wandering traders drop leads when they or their llamas vanishes into thin air, peacefully.

Mod version: Noticed since 1.5.3-Hotfix, still present in 1.6.4.

**Comment by 0xJoeMama** [comment]
This I am not really sure about. Are you sure the traders aren't just being killed off by hostiles?
Again, thank you for your report!

**Comment by 0xJoeMama** [comment]
I need to more information in order to provide a fix for this. I am gonna make a release if the issue persists please let us know.

**Comment by 0xJoeMama** [comment]
Identified: Turns out during the 1.17.1 release there was a bugfix that added a method to check whether a mob can despawn instead of it relying on the entity type. Caravans traders didn't override that method and so they would instantly despawn once 128 blocks away from a player. Thanks for reporting! A release will come out today.
