### ISSUE TITLE
1.18 Port

### ISSUE THREAD

**Issue by Joulanh** [ArshiaDPG/Llamarama#3]
do you intend to update anytime soon ? :D

**Comment by 0xJoeMama** [comment]
Hello. Most of the code for 1.17 is already ready. We were planning on releasing some new llamas as well.
A 1.18 port is possible and easy.

However, due to lack of personal motivation as well as school taking up a good chunk of my time, there is a chance that it won't get ported by me(well there's also a chance that I'll wake up some day and think how about I port llamarama, it won't take that long, and then proceed to spend like 3 days on it lol).

I'll try to do whatever I can but I cannot promise anything for sure.

**Comment by 0xJoeMama** [comment]
> do you intend to update anytime soon ? :D

Also if it is gonna happen it'll most likely be in 1.18.1 since they are releasing it so soon after the big release.

**Comment by Joulanh** [comment]
well, ill patiently wait for the update then,. im happy that the mod is still getting updated would love to play with it

**Comment by 0xJoeMama** [comment]
A new branch has now been created, that contains 1.18 compatible code. A new release will follow up shortly.

**Comment by Joulanh** [comment]
thanks alot!
